# Generated by Django 5.2.6 on 2025-10-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Serving'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('called_time', models.DateTimeField(blank=True, null=True)),
                ('serving_start_time', models.DateTimeField(blank=True, null=True)),
                ('serving_end_time', models.DateTimeField(blank=True, null=True)),
                ('wait_duration', models.PositiveIntegerField(default=0, help_text='Wait duration in minutes')),
                ('service_duration', models.PositiveIntegerField(default=0, help_text='Service duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.counter')),
            ],
            options={
                'ordering': ['queue_number'],
                'indexes': [models.Index(fields=['status', 'queue_number'], name='waiting_que_status_18b6b1_idx'), models.Index(fields=['booking', 'status'], name='waiting_que_booking_c8a36d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaitingQueueMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('average_wait_time', models.PositiveIntegerField(default=0)),
                ('average_service_time', models.PositiveIntegerField(default=0)),
                ('peak_hour', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'unique_together': {('branch', 'service', 'date')},
            },
        ),
    ]
