# Generated by Django 5.2.6 on 2025-10-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingqueue',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitingqueue',
            name='booked_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingqueue',
            name='queue_number',
            field=models.IntegerField(default=0),
        ),
    ]
