# Generated by Django 5.2.6 on 2025-10-01 08:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('priority', 'Priority'), ('vip', 'VIP')], default='normal', max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
                ('token_number', models.CharField(blank=True, max_length=10)),
                ('estimated_wait_time', models.PositiveIntegerField(default=0, help_text='Estimated wait time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['booking_date', 'booking_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.PositiveIntegerField(default=10)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
