# Generated by Django 5.2.6 on 2025-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booking_time_alter_booking_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
