# Generated by Django 5.2.6 on 2025-10-05 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('monitoring_interval', models.IntegerField(default=300)),
                ('use_snmp', models.BooleanField(default=False)),
                ('snmp_community', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('warning', 'Warning'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.devicetype')),
            ],
            options={
                'verbose_name': 'Network Device',
                'verbose_name_plural': 'Network Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SNMPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('1', 'SNMPv1'), ('2c', 'SNMPv2c'), ('3', 'SNMPv3')], default='2c', max_length=3)),
                ('community', models.CharField(default='public', max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('auth_password', models.CharField(blank=True, max_length=100)),
                ('priv_password', models.CharField(blank=True, max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.networkdevice')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('warning', 'Warning'), ('unknown', 'Unknown')], max_length=10)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.networkdevice')),
            ],
            options={
                'verbose_name': 'Device Status History',
                'verbose_name_plural': 'Device Status History',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='monitoring__device__440f30_idx')],
            },
        ),
    ]
