# Generated by Django 5.2.6 on 2025-10-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='operating_hours',
            field=models.TextField(blank=True, help_text='Operating hours description', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('tax', 'Tax Services'), ('customs', 'Customs Services'), ('trade', 'Trade Facilitation'), ('travel', 'Travel Services'), ('other', 'Other Services')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('citizen', 'Citizen'), ('staff', 'Staff'), ('admin', 'Administrator')], default='citizen', max_length=20, null=True),
        ),
    ]
