# Generated by Django 5.2.6 on 2025-10-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
