# Generated by Django 5.2.6 on 2025-10-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@g.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
