# Generated by Django 5.2.6 on 2025-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@g.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='id-num', max_length=20),
        ),
    ]
