# Generated by Django 5.2.6 on 2025-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_email_alter_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='id-num', help_text='National ID or Passport Number eg 22-88888z33', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Include country code, e.g., 263777123123', max_length=15),
        ),
    ]
