# Generated by Django 5.2.6 on 2025-10-10 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('booking_confirmation', 'Booking Confirmation'), ('reminder', 'Reminder'), ('queue_update', 'Queue Update'), ('service_completion', 'Service Completion'), ('system', 'System Notification')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('booking_confirmation', 'Booking Confirmation'), ('reminder', 'Reminder'), ('queue_update', 'Queue Update'), ('service_completion', 'Service Completion'), ('system', 'System Notification')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='message_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject_template',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
