# Generated by Django 5.2.6 on 2025-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('booking_confirmation', 'Booking Confirmation'), ('serving', 'serving'), ('reminder', 'Reminder'), ('queue_update', 'Queue Update'), ('service_completion', 'Service Completion'), ('system', 'System Notification')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('booking_confirmation', 'Booking Confirmation'), ('serving', 'serving'), ('reminder', 'Reminder'), ('queue_update', 'Queue Update'), ('service_completion', 'Service Completion'), ('system', 'System Notification')], max_length=30, null=True),
        ),
    ]
